version: "3"

services:
  php:
    build: .
    container_name: manager-php
    volumes:
      - .:/var/www
    ports:
      - 9000:9000
  nginx:
    image: nginx:latest
    container_name: manager-nginx
    volumes:
        - .:/var/www
        - ./docker/nginx.conf:/etc/nginx/nginx.conf
        - ./docker/project-manager.conf:/etc/nginx/conf.d/default.conf
        - ./docker/php-fpm.ini:/etc/opt/remi/php74/php.ini
    links:
        - php:php
    ports:
        - 80:80
        - 443:443
  postgres:
    image: postgres:13-alpine
    container_name: manager-postgres
    volumes:
      - manager-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: app
    ports:
      - 5432:5432

volumes:
  manager-postgres: