version: "2"

services:
  php:
    build: .
    container_name: project_php
    volumes:
      - .:/var/www
    ports:
      - 9000:9000
  nginx:
    image: nginx:latest
    container_name: project_nginx
    volumes:
        - .:/var/www
        - ./docker/nginx.conf:/etc/nginx/nginx.conf
        - ./docker/project-manager.conf:/etc/nginx/conf.d/default.conf
        - ./docker/php-fpm.ini:/etc/opt/remi/php71/php.ini
    links:
        - php:php
    ports:
        - 80:80
        - 443:443
  project-postgresql:
    image: postgres:13-alpine
    container_name: project-postgresql
    volumes:
      - project-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: app
    ports:
      - "54321:5432"

volumes:
  project-postgres: