version: "2"

services:
  php:
    build: .
    container_name: project_php
    command: asdf
    volumes:
      - .:/var/www
    ports:
      - 9000:9000
  nginx:
    image: nginx:latest
    container_name: project_nginx
    volumes:
        - .:/var/www
        - ./docker/conf/nginx.conf:/etc/nginx/nginx.conf
        - ./docker/conf/tmmarket.conf:/etc/nginx/conf.d/default.conf
        - ./docker/conf/php-fpm-pool.ini:/etc/opt/remi/php71/php-fpm.d/www.conf
        - ./docker/conf/php.ini:/etc/opt/remi/php71/php.ini
    links:
        - php:php
    ports:
        - 80:80
        - 443:443
